apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhttp-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    containers:
      - name: myhttp
        image: dineshkumarkb/myhttp
        ports:
        - containerPort: 8000